name: hello-world
on:
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          echo "Hello World!"
          echo "Test"
          set +e
          ls -2
          echo $?
          set -e
          echo "Bye World!"
